FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive 

RUN apt-get update &&  apt-get install -y \
    openssh-server \
    sudo \
    python3 \
    python3-pip \
    vim \
    wget \
    curl \
    iproute2 \
    iputils-ping \
    net-tools && apt-get clean

RUN mkdir -p /var/run/sshd

RUN useradd -m -s /bin/bash ansible && \
            echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config || true && \
            echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
