FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive 

RUN apt-get update && \
    apt-get install -y \
    openssh-server \
    sudo \
    python3 \
    python3-pip && \
    apt-get clean

RUN mkdir /var/run/sshd

EXPOSE 22

CMD ["/usr/sbin/ssh", "-D"]
