services:
 redis-node-1:
  build: .
  container_name: redis-node-1
  hostname: redis-node-1
  networks:
   - redis-network
 redis-node-2:
  build: .
  container_name: redis-node-2
  hostname: redis-node-2
  networks:
   - redis-network

 redis-node-3:
  build: .
  container_name: redis-node-3
  hostname: redis-node-3
  networks:
   - redis-network

 redis-node-4:
  build: .
  container_name: redis-node-4
  hostname: redis-node-4
  networks:
   - redis-network

 redis-node-5:
  build: .
  container_name: redis-node-5
  hostname: redis-node-5
  networks:
   - redis-network

 redis-node-6:
  build: .
  container_name: redis-node-6
  hostname: redis-node-6
  networks:
   - redis-network

networks:
 redis-network:
  driver: bridge


