[redis_cluster:children]
redis_masters
redis_replicas

[redis_masters]
redis-node-1 ansible_host=127.0.0.1 ansible_port=2211 redis_node_ip=10.250.0.11 redis_port=6379 cluster_bus_port=16379 node_id=1
redis-node-2 ansible_host=127.0.0.1 ansible_port=2212 redis_node_ip=10.250.0.12 redis_port=6379 cluster_bus_port=16379 node_id=2
redis-node-3 ansible_host=127.0.0.1 ansible_port=2213 redis_node_ip=10.250.0.13 redis_port=6379 cluster_bus_port=16379 node_id=3

[redis_replicas]
redis-node-4 ansible_host=127.0.0.1 ansible_port=2214 redis_node_ip=10.250.0.14 redis_port=6379 cluster_bus_port=16379 node_id=4
redis-node-5 ansible_host=127.0.0.1 ansible_port=2215 redis_node_ip=10.250.0.15 redis_port=6379 cluster_bus_port=16379 node_id=5
redis-node-6 ansible_host=127.0.0.1 ansible_port=2216 redis_node_ip=10.250.0.16 redis_port=6379 cluster_bus_port=16379 node_id=6

[redis_cluster:vars]
ansible_user=ansible
ansible_become=yes
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
